package plugin

const manifestLuaFile = `-- This file is automatically generated using "dbee -manifest <file>"
-- DO NOT EDIT!

return function()
  -- Register host
  vim.fn["remote#host#Register"]("{{ .Host }}", "x", function()
    return vim.fn.jobstart({ "{{ .Executable }}" }, {
      rpc = true,
      detach = true,
      on_stderr = function(_, data, _)
        vim.print(data)
      end,
    })
  end)

  -- Manifest
  vim.fn["remote#host#RegisterPlugin"]("{{ .Host }}", "0", {
  {{- range .Specs }}
    { type = "{{ .Type }}", name = "{{ .Name }}", sync = {{ .Sync }}, opts = vim.empty_dict() },
  {{- end }}
  })
end`
