-- This file is automatically generated using CI pipeline
-- DO NOT EDIT!
local M = {}

-- Links to binary releases
M.urls = {
  ["android/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_android_amd64.tar.gz",
  ["android/arm64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_android_arm64.tar.gz",
  ["darwin/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_darwin_amd64.tar.gz",
  ["darwin/arm64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_darwin_arm64.tar.gz",
  ["dragonfly/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_dragonfly_amd64.tar.gz",
  ["freebsd/386"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_freebsd_386.tar.gz",
  ["freebsd/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_freebsd_amd64.tar.gz",
  ["freebsd/arm"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_freebsd_arm.tar.gz",
  ["freebsd/arm64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_freebsd_arm64.tar.gz",
  ["freebsd/riscv64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_freebsd_riscv64.tar.gz",
  ["illumos/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_illumos_amd64.tar.gz",
  ["linux/386"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_386.tar.gz",
  ["linux/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_amd64.tar.gz",
  ["linux/arm"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_arm.tar.gz",
  ["linux/arm64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_arm64.tar.gz",
  ["linux/loong64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_loong64.tar.gz",
  ["linux/mips64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_mips64.tar.gz",
  ["linux/mips64le"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_mips64le.tar.gz",
  ["linux/ppc64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_ppc64.tar.gz",
  ["linux/ppc64le"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_ppc64le.tar.gz",
  ["linux/riscv64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_riscv64.tar.gz",
  ["linux/s390x"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_linux_s390x.tar.gz",
  ["netbsd/386"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_netbsd_386.tar.gz",
  ["netbsd/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_netbsd_amd64.tar.gz",
  ["netbsd/arm"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_netbsd_arm.tar.gz",
  ["netbsd/arm64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_netbsd_arm64.tar.gz",
  ["openbsd/386"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_openbsd_386.tar.gz",
  ["openbsd/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_openbsd_amd64.tar.gz",
  ["openbsd/arm"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_openbsd_arm.tar.gz",
  ["openbsd/arm64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_openbsd_arm64.tar.gz",
  ["openbsd/mips64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_openbsd_mips64.tar.gz",
  ["solaris/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_solaris_amd64.tar.gz",
  ["windows/386"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_windows_386.tar.gz",
  ["windows/amd64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_windows_amd64.tar.gz",
  ["windows/arm"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_windows_arm.tar.gz",
  ["windows/arm64"] = "https://github.com/kndndrj/nvim-dbee/releases/download/v0.1.4/dbee_windows_arm64.tar.gz",
}

-- Git sha of compiled binaries
M.version = "f80ef152f1e694adcda7b43fd15b923efbcd614d"

return M
